### ISSUE TITLE
Case-sensitive specs

### ISSUE THREAD

**Issue by MisterY** [tbocek/dvorak#10]
Hi! 
Something has changed several months ago and dvorak stopped working for me. Following the instructions, I could not manage to make it work again.
Now, after I've installed the system again on a new drive, I decided to give it a go once more, since I really miss the shortcuts.

With some more luck this time, I discovered that the specs in dvorak@.service are now case-sensitive. The `keyb` spec does not work any longer but using `Keyb` works! (actually, I'm using the full word Keyboard).

This issue is just to check if the same happens to others. My previous system was openSuse Thumbleweed and the new one is ArchLinux. Not that it makes a lot of difference, since both are using systemd. But both experienced the same problem initially.

If this is true, I would just update the readme file, the "Not a matching device" section. That should be enough to get one going if the same issue happens.

**Comment by tbocek** [comment]
Hmm, that's odd in https://github.com/tbocek/dvorak/blob/master/dvorak.c#L299 I'm using https://linux.die.net/man/3/strcasestr, which should be case-insensitive. I'll investigate this

**Comment by tbocek** [comment]
Did not find any issues. If the issue is still present, please reopen
