### ISSUE TITLE
Shortcuts from qwerty get altered

### ISSUE THREAD

**Issue by Marlrus** [tbocek/dvorak#12]
After running and installing the file in Ubuntu 20.04 I have shortcuts working on my Dvorak layout. However anything that is not Dvorak gets re-mapped shortcuts. As of now, they aren't even mapped to the Dvorak equivalent. Ctrl + P will refresh, Ctrl + O will print. 

I removed my other language layouts and now only have English US as 1 and English Dvorak as 2. I am in a bind as I cannot find the process that is running this re-mapping and I cannot work effectively in Dvorak yet. I didn't read any of this as expected behaviour in the README.

Cheers!

**Comment by tbocek** [comment]
This is related to #11. So, when running from shell, the keyboard layout gets detected, and only remaps in case of a dvorak layout. However, this does not work when its started on boot. I did not figure out why this is the case.

**Comment by tbocek** [comment]
improved layout detection, this should be fixed now
