### ISSUE TITLE
layout switches to qwerty on first key press

### ISSUE THREAD

**Issue by radi-ka** [tbocek/dvorak#13]
Hi,

when i run this tool from the command line via
`sudo ./dvorak /dev/input/by-path/platform-i8042-serio-0-event-kbd keyb` my layout switches to qwerty permanently on first key pressed. Once i switch back to dvorak it stays there and everything works fine. That first switch is quite irritating though.

I guess I am missing something in my general keyboard config.
Could you please specify where I need to 
> ... ensure that your first keyboard layout is set to Qwerty and your second layout is Dvorak.
?

Do you mean something like this?
`setxkbmap -option grp:ctrls_toggle -layout us,de -variant ,dvorak`

**Comment by tbocek** [comment]
I have now added a better layout detection mechanism that works well with gnome shell. Can you try again?

**Comment by tbocek** [comment]
please reopen if its still an issue

**Comment by radi-ka** [comment]
Hi Thomas

thanks for your reply.
sadly, I am not able to test this as I do not have access to a gnome shell.

but I found a workaround. Instead of  
`_setxkbmap -option grp:ctrls_toggle -layout us,de -variant ,dvorak_`
I start in US layout after boot, then activate the script and then switch to dvorak  
`setxkbmap -layout de -variant ,dvorak`
