### ISSUE TITLE
Segfault when running on Ubuntu 21.10

### ISSUE THREAD

**Issue by ctanner** [tbocek/dvorak#16]
Just built this and when I run it I get a segfault error.

5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

dvorak -d /dev/input/by-id/usb-Razer_Razer_Huntsman_Tournament_Edition_00000000001A-event-kbd

kernel: dvorak[3976]: segfault at 0 ip 00007f24eb6059b7 sp 00007ffc03d2d7f0 error 4 in libc.so.6[7f24eb585000+194000]
kernel: Code: 00 00 90 f3 0f 1e fa 48 8d 15 4d 38 17 00 e9 00 00 00 00 f3 0f 1e fa 41 55 49 89 f5 41 54 49 89 fc 55 48 89 d5 48 85 ff 74 59 <41> 80 3c 24 00 74 42 4c 89 e7 4c 89 ee e8 27 fa f7 ff 49 01 c4 41

**Comment by tbocek** [comment]
Fixed this issue: when no keyword is provided via the -m flag, then it crashed. With this fix (https://github.com/tbocek/dvorak/commit/3aec52cbbf2133fe6b80a53b935ce02ed090aea1), the -m can be omitted without crashing.

Can you try again?

**Comment by ctanner** [comment]
That was fast! Just tried again and it works. I didn't realize the -m flag was required. Thank you for the fix and this project in general. I did get this warning this time. I don't remember seeing it last time it built.

gcc -Wall -O3 -o dvorak dvorak.c
dvorak.c: In function ‘main’:
dvorak.c:219:5: warning: ignoring return value of ‘setuid’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  219 |     setuid(0);
      |     ^~~~~~~~~

**Comment by tbocek** [comment]
The -m flag should not have been required, that was a mistake, but it would have worked with the -m flag :) With respect to the warning, I have removed the setuid, as it is not needed anymore, so the warning should be gone now as well. I'm closing this issue now, thanks for the bug report!
