### ISSUE TITLE
The ' key (Q in QWERTY) does not work in chromium

### ISSUE THREAD

**Issue by hitren0** [tbocek/dvorak#17]
When the service is turned off or I just run dvorak in the terminal, everything works, but when the service is running the upper left key (Q in QWERTY) stops working in chromium on any layouts. At the same time, everything is fine in any other applications. It does not work both when the service is started automatically at startup and when it is started manually. I am using the latest version of Manjaro KDE and Chromium(96.0.4664.110)

**Comment by tbocek** [comment]
I only do a remapping of the Q if isUmlaut is true. Did you set the -u parameter? If you did you need to the dvorak intl. layout with dead keys, otherwise behavior is undefined.

**Comment by tbocek** [comment]
I now also removed this in the service file, I comited -u by accident. Thx for reporting
