### ISSUE TITLE
How to set up for MS wireless Keyboard/Mouse combo?

### ISSUE THREAD

**Issue by nemonein** [tbocek/dvorak#18]
Hello.
First, thank you very much for your effort. I've using Dvorak keyboard since 90's. Yes, it's MS-DOS era. I don't remember why I chose Dvorak, but I'm still stuck on it.
Anyway, my 30 years of struggling has been settled thanks to you. I really appreciate it.
-------
I'm using MS's wireless [keyboard/mouse combo](https://www.amazon.com/Microsoft-Ergonomic-Desktop-Keyboard-L5V-00002/dp/B00DUV01SC/ref=sr_1_2?keywords=microsoft+sculpt+ergonomic&qid=1645014427&sr=8-2).
Here are messages from journalctl.
```
Feb 16 21:15:02 Generousarch dvorak[705]: Not a matching device: [Microsoft Microsoft® 2.4GHz Transceiver v9.0 System Control] does not match these words: [keyb]
Feb 16 21:15:02 Generousarch dvorak[728]: Not a matching device: [Microsoft Microsoft® 2.4GHz Transceiver v9.0] does not match these words: [keyb]
Feb 16 21:15:02 Generousarch dvorak[729]: Not a matching device: [Microsoft Microsoft® 2.4GHz Transceiver v9.0 Consumer Control] does not match these words: [keyb]
Feb 16 21:15:02 Generousarch dvorak[739]: Not a matching device: [Microsoft Microsoft® 2.4GHz Transceiver v9.0 Mouse] does not match these words: [keyb]
Feb 16 21:15:02 Generousarch dvorak[749]: Not a matching device: [Microsoft Microsoft® 2.4GHz Transceiver v9.0 Consumer Control] does not match these words: [keyb]
```

I'm not sure which one is for keyboard. If I choose 'Microsoft', keyboard/mouse does not work at all.
```
ExecStart=/usr/local/bin/dvorak -d /dev/input/%i -m "keyb Microsoft"
```
I've tried with these, but no success.
```
ExecStart=/usr/local/bin/dvorak -d /dev/input/%i -m "keyb System Control"
ExecStart=/usr/local/bin/dvorak -d /dev/input/%i -m "keyb Transceiver v9.0"
```
Finally, I could make it work with this, but it's not what this command for.
```
ExecStart=/usr/local/bin/dvorak -d /dev/input/by-id/usb-Microsoft_Microsoft®_2.4GHz_Transceiver_v9.0-event-kbdd
```

Is is possible to detect this keyboard?

**Comment by tbocek** [comment]
If you know the exact device id, you don't need to specify the string match.
