### ISSUE TITLE
quote key not firing

### ISSUE THREAD

**Issue by stephenmdc** [tbocek/dvorak#24]
for whatever reason when running dvorak I can't get the quote (') key, in qwerty this is the q, to fire.
Not sure why but I would love to use this software otherwise

**Comment by tbocek** [comment]
That's weird... if you use dvorak alt international, it may be a deadkey. So by pressing another key, the other key can get modified.

**Comment by stephenmdc** [comment]
I figured it out. It was the international key just need to add the option.
