### ISSUE TITLE
"Fatal error" while `make`

### ISSUE THREAD

**Issue by lotc** [tbocek/dvorak#27]
Try to `make` on a fresh install Linux.
report that
```
dvorak.c:64:10: fatal error: stdlib.h: No such file or directory
    64  |  #include <stdlib.h>
compilation terminated
make: *** [Makefile:13: all] Error 1
```

Is the problem of my GCC version or the code itself?

**Comment by tbocek** [comment]
Sorry for the late response, you need the dev libraries for libc. Something like this should help if you are using Ubuntu:

```sudo apt-get install libc6-dev ```

Depending on your distro, the command may look different.

**Comment by lotc** [comment]
Alright, I will take a try.
I'm using Linux Mint. Since it's Debian-based, I think it should work.
Thanks for your reply.
