### ISSUE TITLE
How to install??

### ISSUE THREAD

**Issue by Feliks-WR** [tbocek/dvorak#28]
Please publish a .deb package.
Can't figure out how to properly install.

**Comment by Contruffin** [comment]
Figured it out. Here's what to do:

1. Make sure that make and gcc are installed. On terminal, run `sudo apt install make` and `sudo apt install gcc`
2. In the main page of this project (the code tab), click on the green "code" button, and then select the option to download ZIP
3. Find where the ZIP file downloaded to, and extract everything in the folder
4. Open up the folder, and open terminal in the folder location (There should be an option in your file browser). You should also be able to do `cd location_of_folder`
5. In the terminal, run `make`. There should only be a single line of output
6. Then, run `sudo make install`

**Comment by Feliks-WR** [comment]
Got it 👍
It is listed on README.md

However, how do I uninstall this?

-- عبداللہ قاسم
________________________________

**Comment by tbocek** [comment]
To unintall, you can type (if you are not root, use sudo):

```
systemctl stop 'dvorak@*.service'
rm /usr/local/bin/dvorak
rm /etc/udev/rules.d/80-dvorak.rules
rm /etc/systemd/system/dvorak@.service
udevadm control --reload
systemctl restart systemd-udevd.service
systemctl daemon-reload
```

I also updated the readme file
