### ISSUE TITLE
Long boot time when installed

### ISSUE THREAD

**Issue by Contruffin** [tbocek/dvorak#29]
Installed the script and noticed that while it's installed, the boot time is around 2 minutes. I tracked it down to `systemd-udev-settle.service`. Something in the code seems to be calling this service, which seems to cause the computer to wait for 2 minutes while devices load. This service appears to be deprecated, and regular boot times can be restored to regular times with `systemctl mask systemd-udev-settle.service`.

It seems Ubuntu hasn't disabled this service, so the install procedure should probably also mask this service if it exists. (Or, at least mention this issue in the readme)

**Comment by tbocek** [comment]
Interesting, I just removed the Intall target from the systemd unit file, which seems unnecessary. Can you try again? If its not working, I´ll update the readme.

**Comment by Contruffin** [comment]
The new version doesn't appear to solve the issue

**Comment by tbocek** [comment]
Thx for trying! I added your workaround to the readme in aab73258e5a9fcf416f7c902af8dcea0bc62bc80
