### ISSUE TITLE
Support for multiple keyboard layouts?

### ISSUE THREAD

**Issue by notthebee** [tbocek/dvorak#8]
I use two keyboard layouts on my computer - Dvorak and Russian. It says in the README that the first keyboard layout should be set to QWERTY, and the second one to Dvorak. However, that would interfere with layout switching. Is there any way to use this project and still keep the third layout?

**Comment by tbocek** [comment]
Yes, currently this is an issue, if you switch the layout, the mapping is still in place. I'm playing with ways how to detect if the layout is dvorak, and only enable the mapping if a dvorak layout is active. However, I could not reliably get the name of the keyboard layout yet.

**Comment by tbocek** [comment]
Finally added

**Comment by erik-balfe** [comment]
Could anyone share a way, how to make it work with other layouts? Currently the mapping is applied to all layouts and the only way to fix it is to press L ALT 3 times after every layout switch
