### ISSUE TITLE
Which keycodes are which keys?

### ISSUE THREAD

**Issue by Zazcallabah** [tbocek/dvorak#9]
I'm using this with my custom layout and it is working fine except for one thing. My layout doesn't move the + and = keys, so when for example I try to resize text it triggers the wrong keys.

I'm thinking I could fix this by just removing the proper lines in the large switch-case, but I don't know how to figure out which keys map to which key codes?

**Comment by tbocek** [comment]
you can check the keycodes with ```sudo showkey --scancodes```

**Comment by Zazcallabah** [comment]
Thanks! :)

Which process do I need to kill to unlock `/usr/bin/dvorak` so i can rerun make install?

**Comment by Zazcallabah** [comment]
Thanks! :)
Removed the lines and now I think it works the way I want.
